apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: topology.ebs.csi.aws.com/zone
                    operator: In
                    values:
                      - ap-south-1a
                  - key: topology.kubernetes.io/region
                    operator: In
                    values:
                      - ap-south-1
      initContainers:
        - name: init-permissions
          image: busybox
          command: ['sh', '-c', 'chown -R 65534:65534 /prometheus'] # Ensure Prometheus has ownership of the volume
          volumeMounts:
            - mountPath: /prometheus      # Mount path of the volume inside the init container
              name: prometheus-home      # Name of the Persistent Volume for Prometheus data
      containers:
        - name: prometheus
          image: prom/prometheus:v2.37.0 # Use the correct Prometheus image version
          imagePullPolicy: Always
          ports:
            - containerPort: 9090  # Prometheus Web UI port
          volumeMounts:
            - name: prometheus-home
              mountPath: /prometheus  # Mount path for the Prometheus data inside the container
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"  # Path to the Prometheus config file (ensure the file is mounted)
            - "--storage.tsdb.path=/prometheus"  # Directory where Prometheus stores its time-series data
            - "--web.listen-address=0.0.0.0:9090"  # Web UI listen address
      volumes:
        - name: prometheus-home
          persistentVolumeClaim:
            claimName: prometheus-pvc  # Ensure that the PVC name is correct and exists

