apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  labels:
    app: httpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
        - name: httpd
          image: httpd:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: httpd-volume
              mountPath: /usr/local/apache2/htdocs  # Default path where HTTPD serves files
      volumes:
        - name: httpd-volume
          persistentVolumeClaim:
            claimName: httpd-pvc  # PVC that you created earlier

