apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: jenkins-storage
provisioner: kubernetes.io/aws-ebs  # Ensure this matches your cloud provider
parameters:
  type: gp2  # Or the correct volume type based on your cloud provider (AWS, GCP, etc.)
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowedTopologies:
  - matchLabelExpressions:
      - key: topology.kubernetes.io/zone  # Use the new recommended key
        values:
          - ap-south-1a  # Replace with your zone

