apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: jenkins-storage
provisioner: kubernetes.io/aws-ebs  # Replace with your cloud provider if different
parameters:
  type: gp2  # You can adjust this based on your cloud provider's options
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer  # This ensures volume is provisioned after the first pod is scheduled
